In [1]:
import pandas as pd

In [3]:
data=pd.Series([1,2,3,4,5])
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
pd.read_csv("employees.csv")

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
0,1001,Employee_01,Sales,Mumbai,Female,27,40708.0,15.0,Excellent,2021-01-01
1,1002,Employee_02,Marketing,Pune,Female,26,116906.0,13.0,Poor,2021-02-15
2,1003,Employee_03,Finance,Hyderabad,Male,28,74811.0,1.0,Poor,2021-04-01
3,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
4,1005,Employee_05,Marketing,Mumbai,Male,25,81250.0,5.0,Excellent,2021-06-30
...,...,...,...,...,...,...,...,...,...,...
57,1058,Employee_58,HR,Delhi,Male,29,107018.0,15.0,Good,2028-01-10
58,1059,Employee_59,Sales,Bengaluru,Male,26,27200.0,0.0,Poor,2028-02-24
59,1060,Employee_60,HR,Mumbai,Male,36,93497.0,15.0,Average,2028-04-09
60,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
61,1016,Employee_16,HR,Mumbai,Male,37,113614.0,15.0,Good,2022-11-07

In [20]:
df.head(5)

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
0,1001,Employee_01,Sales,Mumbai,Female,27,40708.0,15.0,Excellent,2021-01-01
1,1002,Employee_02,Marketing,Pune,Female,26,116906.0,13.0,Poor,2021-02-15
2,1003,Employee_03,Finance,Hyderabad,Male,28,74811.0,1.0,Poor,2021-04-01
3,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
4,1005,Employee_05,Marketing,Mumbai,Male,25,81250.0,5.0,Excellent,2021-06-30

In [21]:
df.tail(5)

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
57,1058,Employee_58,HR,Delhi,Male,29,107018.0,15.0,Good,2028-01-10
58,1059,Employee_59,Sales,Bengaluru,Male,26,27200.0,0.0,Poor,2028-02-24
59,1060,Employee_60,HR,Mumbai,Male,36,93497.0,15.0,Average,2028-04-09
60,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
61,1016,Employee_16,HR,Mumbai,Male,37,113614.0,15.0,Good,2022-11-07

In [22]:
df.shape

(62, 10)

In [25]:
df.size

620

In [26]:
df.describe()

       Employee_ID        Age         Salary  Experience_Years
count    62.000000  62.000000      59.000000         61.000000
mean   1029.838710  32.419355   65585.491525          7.442623
std      17.593025   7.696174   30013.454425          5.442195
min    1001.000000  21.000000   26802.000000          0.000000
25%    1015.250000  26.000000   36797.000000          2.000000
50%    1029.500000  32.000000   63360.000000          6.000000
75%    1044.750000  39.000000   91980.000000         13.000000
max    1060.000000  44.000000  116906.000000         15.000000

In [31]:
df.isnull()

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False,False

In [33]:
df.fillna

<bound method NDFrame.fillna of     Employee_ID         Name Department       City  Gender  Age    Salary  \
0          1001  Employee_01      Sales     Mumbai  Female   27   40708.0
1          1002  Employee_02  Marketing       Pune  Female   26  116906.0
2          1003  Employee_03    Finance  Hyderabad    Male   28   74811.0
3          1004  Employee_04  Marketing     Mumbai    Male   29   27811.0
4          1005  Employee_05  Marketing     Mumbai    Male   25   81250.0
..          ...          ...        ...        ...     ...  ...       ...
57         1058  Employee_58         HR      Delhi    Male   29  107018.0
58         1059  Employee_59      Sales  Bengaluru    Male   26   27200.0
59         1060  Employee_60         HR     Mumbai    Male   36   93497.0
60         1004  Employee_04  Marketing     Mumbai    Male   29   27811.0
61         1016  Employee_16         HR     Mumbai    Male   37  113614.0

    Experience_Years Performance Joining_Date
0               15.0   Excellent   2021-01-01
1               13.0        Poor   2021-02-15
2                1.0        Poor   2021-04-01
3                1.0        Good   2021-05-16
4                5.0   Excellent   2021-06-30
..               ...         ...          ...
57              15.0        Good   2028-01-10
58               0.0        Poor   2028-02-24
59              15.0     Average   2028-04-09
60               1.0        Good   2021-05-16
61              15.0        Good   2022-11-07

[62 rows x 10 columns]>