Data manipulation and analysis are key task in any data science or data analysis project 

pandas provide a wide range of functions for manipulation and analysis making it easer to clean transform and extract from data

In [1]:
import pandas as pd

In [3]:
import io

csv_data = """Employee_ID,Name,Department,Age,Salary,Joining_Date,Performance_Score
101,Alice,HR,28,55000,2021-01-15,85
102,Bob,Engineering,,72000,2020-03-22,
103,Charlie,,35,68000,,90
104,David,Engineering,42,NA,2018-11-05,78
105,Eva,Marketing,29,61000,2022-07-01,N/A
106,Frank,HR,,52000,2019-05-18,65
107,Grace,Sales,31,?,2021-09-12,88
108,Hank,Engineering,50,95000,2015-02-28,92
109,Ivy,,26,48000,2023-01-10,
110,Jack,Marketing,38,70000,2019-12-01,81
"""

In [5]:
df = pd.read_csv(io.StringIO(csv_data), na_values=['NA', 'N/A', '?'])

In [6]:
df

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Performance_Score
0,101,Alice,HR,28.0,55000.0,2021-01-15,85.0
1,102,Bob,Engineering,NaN,72000.0,2020-03-22,NaN
2,103,Charlie,NaN,35.0,68000.0,NaN,90.0
3,104,David,Engineering,42.0,NaN,2018-11-05,78.0
4,105,Eva,Marketing,29.0,61000.0,2022-07-01,NaN
5,106,Frank,HR,NaN,52000.0,2019-05-18,65.0
6,107,Grace,Sales,31.0,NaN,2021-09-12,88.0
7,108,Hank,Engineering,50.0,95000.0,2015-02-28,92.0
8,109,Ivy,NaN,26.0,48000.0,2023-01-10,NaN
9,110,Jack,Marketing,38.0,70000.0,2019-12-01,81.0

In [9]:
df.isnull().any()

Employee_ID          False
Name                 False
Department            True
Age                   True
Salary                True
Joining_Date          True
Performance_Score     True
dtype: bool

In [10]:
df.isnull().sum()

Employee_ID          0
Name                 0
Department           2
Age                  2
Salary               2
Joining_Date         1
Performance_Score    3
dtype: int64

In [17]:
df['Salary_fillna']=df['Salary'].fillna(df['Salary'].mean())
df

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Performance_Score,sal_fillna,Salary_fillna
0,101,Alice,HR,28.0,55000.0,2021-01-15,85.0,55000.0,55000.0
1,102,Bob,Engineering,NaN,72000.0,2020-03-22,NaN,72000.0,72000.0
2,103,Charlie,NaN,35.0,68000.0,NaN,90.0,68000.0,68000.0
3,104,David,Engineering,42.0,NaN,2018-11-05,78.0,65125.0,65125.0
4,105,Eva,Marketing,29.0,61000.0,2022-07-01,NaN,61000.0,61000.0
5,106,Frank,HR,NaN,52000.0,2019-05-18,65.0,52000.0,52000.0
6,107,Grace,Sales,31.0,NaN,2021-09-12,88.0,65125.0,65125.0
7,108,Hank,Engineering,50.0,95000.0,2015-02-28,92.0,95000.0,95000.0
8,109,Ivy,NaN,26.0,48000.0,2023-01-10,NaN,48000.0,48000.0
9,110,Jack,Marketing,38.0,70000.0,2019-12-01,81.0,70000.0,70000.0

In [26]:
df['Performance_Score_filled']=df['Performance_Score'].fillna(df['Performance_Score'].mean())
df

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Performance_Score,sal_fillna,Salary_fillna,Performance_Score_filled
0,101,Alice,HR,28.0,55000.0,2021-01-15,85.0,55000.0,55000.0,85.000000
1,102,Bob,Engineering,NaN,72000.0,2020-03-22,NaN,72000.0,72000.0,82.714286
2,103,Charlie,NaN,35.0,68000.0,NaN,90.0,68000.0,68000.0,90.000000
3,104,David,Engineering,42.0,NaN,2018-11-05,78.0,65125.0,65125.0,78.000000
4,105,Eva,Marketing,29.0,61000.0,2022-07-01,NaN,61000.0,61000.0,82.714286
5,106,Frank,HR,NaN,52000.0,2019-05-18,65.0,52000.0,52000.0,65.000000
6,107,Grace,Sales,31.0,NaN,2021-09-12,88.0,65125.0,65125.0,88.000000
7,108,Hank,Engineering,50.0,95000.0,2015-02-28,92.0,95000.0,95000.0,92.000000
8,109,Ivy,NaN,26.0,48000.0,2023-01-10,NaN,48000.0,48000.0,82.714286
9,110,Jack,Marketing,38.0,70000.0,2019-12-01,81.0,70000.0,70000.0,81.000000

In [27]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Performance_Score,sal_fillna,Salary_fillna,Performance_Score_filled
0,101,Alice,HR,28.000,55000.0,2021-01-15,85.0,55000.0,55000.0,85.000000
1,102,Bob,Engineering,34.875,72000.0,2020-03-22,NaN,72000.0,72000.0,82.714286
2,103,Charlie,NaN,35.000,68000.0,NaN,90.0,68000.0,68000.0,90.000000
3,104,David,Engineering,42.000,NaN,2018-11-05,78.0,65125.0,65125.0,78.000000
4,105,Eva,Marketing,29.000,61000.0,2022-07-01,NaN,61000.0,61000.0,82.714286
5,106,Frank,HR,34.875,52000.0,2019-05-18,65.0,52000.0,52000.0,65.000000
6,107,Grace,Sales,31.000,NaN,2021-09-12,88.0,65125.0,65125.0,88.000000
7,108,Hank,Engineering,50.000,95000.0,2015-02-28,92.0,95000.0,95000.0,92.000000
8,109,Ivy,NaN,26.000,48000.0,2023-01-10,NaN,48000.0,48000.0,82.714286
9,110,Jack,Marketing,38.000,70000.0,2019-12-01,81.0,70000.0,70000.0,81.000000