In [2]:
import pandas as pd

In [3]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("series\n",series)
print(type(data))
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'list'>
<class 'pandas.core.series.Series'>

In [4]:
## creating series from dictionary

data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index_name=['a','b','c']
pd.Series(data,index=index_name)

a    10
b    20
c    30
dtype: int64

In [6]:
## creating dataframe form a dictionary list

data={
    'name':['arun','varun','shivu'],
    'age':[25,26,27],
    'city':['bengaluru','belagavi','hubbli']
}

df=pd.DataFrame(data)
print(df)
df

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27     hubbli

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27     hubbli

In [7]:
### creating dataframe from list of dictionares
data=[
    {'name':'arun','age':25,'city':'bengaluru'},
    {'name':'varun','age':26,'city':'belagavi',},
    {'name':'shivu','age':27,'city':'hubli',}
]

df= pd.DataFrame(data)
print(df)
df

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27      hubli

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27      hubli

## Reading csv file using pandas with some exmp

In [8]:
df=pd.read_csv("employees.csv")

In [9]:
df.head(5)

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
0,1001,Employee_01,Sales,Mumbai,Female,27,40708.0,15.0,Excellent,2021-01-01
1,1002,Employee_02,Marketing,Pune,Female,26,116906.0,13.0,Poor,2021-02-15
2,1003,Employee_03,Finance,Hyderabad,Male,28,74811.0,1.0,Poor,2021-04-01
3,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
4,1005,Employee_05,Marketing,Mumbai,Male,25,81250.0,5.0,Excellent,2021-06-30

In [10]:
df['Name']

0     Employee_01
1     Employee_02
2     Employee_03
3     Employee_04
4     Employee_05
         ...
57    Employee_58
58    Employee_59
59    Employee_60
60    Employee_04
61    Employee_16
Name: Name, Length: 62, dtype: object

## accesing specific row in dataframe using df.loc[]

In [11]:
df.loc[0]

Employee_ID                1001
Name                Employee_01
Department                Sales
City                     Mumbai
Gender                   Female
Age                          27
Salary                  40708.0
Experience_Years           15.0
Performance           Excellent
Joining_Date         2021-01-01
Name: 0, dtype: object

In [12]:
df.loc[5]

Employee_ID                1006
Name                Employee_06
Department                   HR
City                       Pune
Gender                   Female
Age                          21
Salary                      NaN
Experience_Years            2.0
Performance                Good
Joining_Date         2021-08-14
Name: 5, dtype: object

## accessing a specific element

In [13]:
age=df.at[2,'Age']
print("Age:",age)

Age: 28

In [14]:
df.at[0,'Performance']

'Excellent'

## data maniplution with data frame

In [15]:
### creating dataframe from list of dictionares
data=[
    {'name':'arun','age':25,'city':'bengaluru'},
    {'name':'varun','age':26,'city':'belagavi',},
    {'name':'shivu','age':27,'city':'hubli',}
]

df= pd.DataFrame(data)
df

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27      hubli

In [27]:
## creating dataframe form a dictionary list

data={
    'name':['arun','varun','shivu'],
    'age':[25,26,27],
    'city':['bengaluru','belagavi','hubbli']
}

df=pd.DataFrame(data)
df

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27     hubbli

In [17]:
data=pd.Series([1,2,3,4,5])
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [28]:
df

    name  age       city
0   arun   25  bengaluru
1  varun   26   belagavi
2  shivu   27     hubbli

In [34]:
df['age']=df['age']+1

TypeError: list indices must be integers or slices, not str

In [18]:
df=pd.read_csv("employees.csv")

In [19]:
df.head()

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
0,1001,Employee_01,Sales,Mumbai,Female,27,40708.0,15.0,Excellent,2021-01-01
1,1002,Employee_02,Marketing,Pune,Female,26,116906.0,13.0,Poor,2021-02-15
2,1003,Employee_03,Finance,Hyderabad,Male,28,74811.0,1.0,Poor,2021-04-01
3,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
4,1005,Employee_05,Marketing,Mumbai,Male,25,81250.0,5.0,Excellent,2021-06-30

In [20]:
df.tail(5)

,Employee_ID,Name,Department,City,Gender,Age,Salary,Experience_Years,Performance,Joining_Date
57,1058,Employee_58,HR,Delhi,Male,29,107018.0,15.0,Good,2028-01-10
58,1059,Employee_59,Sales,Bengaluru,Male,26,27200.0,0.0,Poor,2028-02-24
59,1060,Employee_60,HR,Mumbai,Male,36,93497.0,15.0,Average,2028-04-09
60,1004,Employee_04,Marketing,Mumbai,Male,29,27811.0,1.0,Good,2021-05-16
61,1016,Employee_16,HR,Mumbai,Male,37,113614.0,15.0,Good,2022-11-07

In [21]:
df.shape

(62, 10)

In [22]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'City', 'Gender', 'Age', 'Salary',
       'Experience_Years', 'Performance', 'Joining_Date'],
      dtype='object')

In [23]:
df.dtypes

Employee_ID           int64
Name                 object
Department           object
City                 object
Gender               object
Age                   int64
Salary              float64
Experience_Years    float64
Performance          object
Joining_Date         object
dtype: object

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       62 non-null     int64
 1   Name              62 non-null     object
 2   Department        62 non-null     object
 3   City              60 non-null     object
 4   Gender            62 non-null     object
 5   Age               62 non-null     int64
 6   Salary            59 non-null     float64
 7   Experience_Years  61 non-null     float64
 8   Performance       60 non-null     object
 9   Joining_Date      62 non-null     object
dtypes: float64(2), int64(2), object(6)
memory usage: 5.0+ KB

In [25]:
df.describe()

       Employee_ID        Age         Salary  Experience_Years
count    62.000000  62.000000      59.000000         61.000000
mean   1029.838710  32.419355   65585.491525          7.442623
std      17.593025   7.696174   30013.454425          5.442195
min    1001.000000  21.000000   26802.000000          0.000000
25%    1015.250000  26.000000   36797.000000          2.000000
50%    1029.500000  32.000000   63360.000000          6.000000
75%    1044.750000  39.000000   91980.000000         13.000000
max    1060.000000  44.000000  116906.000000         15.000000